### ISSUE TITLE
Project needs a Visual Studio project file

### ISSUE THREAD

**Issue by DanRStevens** [OutpostUniverse/JsonMap#1]
This project needs a Visual Studio project file for compiling with MSVC. Currently it only has a `makefile` for compiling on Linux with GCC or Clang.

**Comment by Brett208** [comment]
What settings are you thinking. Taking a stab in the dark, I would consider starting with:

- statically link against OP2Utility and nlohmann::json
- Use nuget package for nlohmann::json (I think this could be a submodule as well since it is maintained in a Git repository)
- C++17 standard
- standard x86 and x64 compilation
- standard Debug and Release builds
- Visual Studio project and solution file in the root directory next to the make file

-Brett

**Comment by DanRStevens** [comment]
That sounds exactly right.

There is already a `packages.config` for the NuGet packages. I assume the Solution or Project file just has to reference it.

Should we place the Project file in the repository root for simple project like this, or should that go in the `src/` folder? The Solution file should certain be in the repository root. I was just thinking AppVeyor gets confused if it sees both a Solution and Project file, and you don't specify which one it should build. I'm not sure if it recursively searches directories though.

**Comment by Brett208** [comment]
I see both patterns of putting the project file next to the solution and in a subfolder in common use. Happy to put it in the src directory (or other way around if you prefer).
